import { NextResponse } from "next/server";

export async function GET() {
  const doctors = [
    {
      id: "1",
      name: "Dr. Prakash Das",
      email: "prakash.das@hospital.com",
      phone: "9876543201",             // updated field name
      location: "Kolkata, India",
      specialization: "Psychologist",
      experience: "7 years",
      rating: 4.7,
      profileImage: "https://img.freepik.com/free-photo/portrait-smiling-male-doctor_171337-1532.jpg",
      availability: "Available today",
      workingHours: "09:30 AM – 07:00 PM", // updated field name
      description: "As a Psychologist, Dr. Das has practiced for over 7 years, helping patients overcome mental health challenges with personalized therapies.",
    },
    {
      id: "2",
      name: "Dr. Neha Kapoor",
      email: "neha.kapoor@hospital.com",
      phone: "9876543202",
      location: "Delhi, India",
      specialization: "Pediatrician",
      experience: "5 years",
      rating: 4.8,
      profileImage: "https://img.freepik.com/free-photo/portrait-smiling-female-doctor_171337-1535.jpg",
      availability: "Available today",
      workingHours: "10:00 AM – 06:00 PM",
      description: "Dr. Neha is a child care expert with 5+ years of experience in pediatric health and child wellness programs.",
    },
    {
      id: "3",
      name: "Dr. Arun Mehta",
      email: "arun.mehta@hospital.com",
      phone: "9876543203",
      location: "Mumbai, India",
      specialization: "Cardiologist",
      experience: "10 years",
      rating: 4.9,
      profileImage: "https://img.freepik.com/free-photo/portrait-handsome-male-doctor-white-coat_171337-1536.jpg",
      availability: "Available today",
      workingHours: "11:00 AM – 08:00 PM",
      description: "Specialist in heart diseases with 10+ years of experience in cardiac care, diagnosis, and preventive treatments.",
    },
    {
      id: "4",
      name: "Dr. Riya Sharma",
      email: "riya.sharma@hospital.com",
      phone: "9876543204",
      location: "Pune, India",
      specialization: "Dermatologist",
      experience: "8 years",
      rating: 4.6,
      profileImage: "https://img.freepik.com/free-photo/portrait-smiling-female-doctor_171337-1535.jpg",
      availability: "Available today",
      workingHours: "09:00 AM – 05:00 PM",
      description: "Expert in skincare, acne, and cosmetic treatments with 8+ years of clinical experience in dermatology.",
    },
    {
      id: "5",
      name: "Dr. Karan Bhatia",
      email: "karan.bhatia@hospital.com",
      phone: "9876543205",
      location: "Chandigarh, India",
      specialization: "Orthopedic Surgeon",
      experience: "12 years",
      rating: 4.8,
      profileImage: "https://img.freepik.com/free-photo/portrait-smiling-female-doctor_171337-1535.jpg",
      availability: "Available today",
      workingHours: "08:30 AM – 04:00 PM",
      description: "Specialist in bone and joint surgeries with 12+ years of experience in trauma and sports orthopedics.",
    },
    {
      id: "6",
      name: "Dr. Meenal Rajput",
      email: "meenal.rajput@hospital.com",
      phone: "9876543206",
      location: "Jaipur, India",
      specialization: "Gynecologist",
      experience: "9 years",
      rating: 4.7,
      profileImage: "https://img.freepik.com/free-photo/portrait-smiling-female-doctor_171337-1535.jpg",
      availability: "Available today",
      workingHours: "10:30 AM – 06:30 PM",
      description: "Focused on women's health and maternity care for over 9 years with expertise in pregnancy and fertility care.",
    },
    {
      id: "7",
      name: "Dr. Rohit Sinha",
      email: "rohit.sinha@hospital.com",
      phone: "9876543207",
      location: "Lucknow, India",
      specialization: "Neurologist",
      experience: "11 years",
      rating: 4.9,
      profileImage: "https://img.freepik.com/free-photo/portrait-smiling-female-doctor_171337-1535.jpg",
      availability: "Available today",
      workingHours: "11:00 AM – 07:00 PM",
      description: "Specialist in brain and nervous system disorders, practicing for 11+ years in clinical and diagnostic neurology.",
    },
    {
      id: "8",
      name: "Dr. Anjali Verma",
      email: "anjali.verma@hospital.com",
      phone: "9876543208",
      location: "Hyderabad, India",
      specialization: "Dentist",
      experience: "6 years",
      rating: 4.6,
      profileImage: "https://img.freepik.com/free-photo/portrait-smiling-female-doctor_171337-1535.jpg",
      availability: "Available today",
      workingHours: "09:00 AM – 05:00 PM",
      description: "Expert in oral hygiene, cosmetic dentistry, and dental surgeries with 6+ years of experience.",
    },
    {
      id: "9",
      name: "Dr. John Smith",
      email: "dr.smith@hospital.com",
      phone: "9876543220",
      location: "Mumbai, India",
      specialization: "Cardiologist",
      experience: "15 years",
      rating: 4.8,
      profileImage: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400",
      availability: "Available today",
      workingHours: "10:00 AM – 07:00 PM",
      description: "Highly experienced cardiologist with 15 years in interventional and preventive heart care.",
    },
    {
      id: "10",
      name: "Dr. Sarah Johnson",
      email: "dr.sarah@hospital.com",
      phone: "9876543221",
      location: "Delhi, India",
      specialization: "Neurologist",
      experience: "12 years",
      rating: 4.9,
      profileImage: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
      availability: "Available today",
      workingHours: "09:30 AM – 06:30 PM",
      description: "Expert in complex neurological disorders with 12+ years of experience in brain and spinal care.",
    },
    {
      id: "11",
      name: "Dr. Mike Wilson",
      email: "dr.mike@hospital.com",
      phone: "9876543222",
      location: "Bangalore, India",
      specialization: "Orthopedic Surgeon",
      experience: "10 years",
      rating: 4.7,
      profileImage: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
      availability: "Available today",
      workingHours: "08:00 AM – 04:00 PM",
      description: "Dedicated orthopedic surgeon with 10 years of experience in fracture management and joint replacement.",
    },
    {
      id: "12",
      name: "Dr. Priya Patel",
      email: "dr.priya@hospital.com",
      phone: "9876543223",
      location: "Ahmedabad, India",
      specialization: "Dermatologist",
      experience: "8 years",
      rating: 4.6,
      profileImage: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400",
      availability: "Available today",
      workingHours: "09:30 AM – 05:30 PM",
      description: "Skin care expert specializing in acne, pigmentation, and anti-aging treatments with 8 years of experience.",
    },
  ];

  return NextResponse.json(doctors);
}
